name: noteplan
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  intl: ^0.18.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.4
  build_runner: ^2.4.6
  firebase_database: ^10.2.4
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logingoogle.png
    - assets/logo/people.png
    - assets/logo/password.png
    - assets/logo/google.png
    - assets/logo/notes.png
    - assets/logo/notes2.png
    - assets/logo/back.png
    - assets/logo/reset.png
    - assets/images/thinking.png
    - assets/images/idea.png
    - assets/icons/bold.png
    - assets/icons/italic.png
    - assets/icons/image.png

  fonts:
    - family: wixmadefor
      fonts:
        - asset: assets/fonts/wixmadefor.ttf
    - family: ubuntu
      fonts:
        - asset : assets/fonts/ubuntu.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/montserrat.ttf